class Card {
  int index;
  int nativeIndex;
  String eng;
  String ger;
  String plural;
  String type;
  String category;
  Card(this.index, this.nativeIndex, this.ger, this.plural, this.eng, this.type, this.category);
}


List<Card> mainCardList = [
  Card(0, 800, "zählen", "", "to count", "verb", "Numbers"),
  Card(1, 2, "die Person", "Personen", "person", "noun", "Human Beings"),
  Card(2, 33, "das Kleid", "Kleider", "dress", "noun", "Human Beings"),
  Card(3, 1, "der Mensch", "Menschen", "man, person", "noun", "Human Beings"),
  Card(4, 4, "wohnen", "", "to live", "verb", "Human Beings"),
  Card(5, 5, "die Frau", "Frauen", "woman, Mrs, Ms", "", "Human Beings"),
  Card(6, 6, "der Mann", "Männer", "man", "", "Human Beings"),
  Card(7, 7, "der Herr", "Herren", "Mr", "", "Human Beings"),
  Card(8, 8, "die Dame", "Damen", "lady", "noun", "Human Beings"),
  Card(9, 9, "der Junge", "Jungen", "boy", "noun ", "Human Beings"),
  Card(10, 10, "das Mädchen", "Mädchen", "girl", "noun", "Human Beings"),
  Card(11, 3, "leben", "", "to live", "verb", "Human Beings"),
  Card(12, 14, "schwer", "", "heavy", "adjective", "Human Beings"),
  Card(13, 11, "die Adresse", "Adressen", "address", "noun", "Human Beings"),
  Card(14, 12, "der Name", "Namen", "name", "noun", "Human Beings"),
  Card(15, 13, "groß", "", "big", "adjective", "Human Beings"),
  Card(16, 15, "klein", "", "small, little", "adjective", "Human Beings"),
  Card(17, 16, "schön", "", "beautiful, nice", "adjective", "Human Beings"),
  Card(18, 17, "nett", "", "nice, kind", "adjective", "Human Beings"),
  Card(19, 18, "jung", "", "young", "adjective", "Human Beings"),
  Card(20, 19, "alt", "", "old", "adjective", "Human Beings"),
  Card(21, 20, "schlank", "", "slim", "adjective", "Human Beings"),
  Card(22, 21, "dünn", "", "thin", "adjective", "Human Beings"),
  Card(23, 22, "hübsch", "", "pretty", "adjective", "Human Beings"),
  Card(24, 23, "aussehen", "", "to look", "verb", "Human Beings"),
  Card(25, 24, "die Kleidung", "kein Pl", "clothes", "noun", "Human Beings"),
  Card(26, 25, "anziehen", "", "put on, to dress", "verb", "Human Beings"),
  Card(27, 26, "anprobieren", "", "to try on", "verb", "Human Beings"),
  Card(28, 27, "der Pullover", "Pullover", "pullover, sweater", "noun", "Human Beings"),
  Card(29, 28, "die Hose", "Hosen", "trousers", "noun", "Human Beings"),
  Card(30, 29, "die Jeans", "Jeans", "jeans", "noun", "Human Beings"),
  Card(31, 30, "der Schuh", "Schuhe", "shoe", "noun", "Human Beings"),
  Card(32, 31, "das Hemd", "Hemden", "shirt", "noun", "Human Beings"),
  Card(33, 32, "die Bluse", "Blusen", "blouse", "noun", "Human Beings"),
  Card(34, 34, "der Rock", "Röcke", "skirt", "noun", "Human Beings"),
  Card(35, 35, "der Anzug", "Anzüge", "suit", "noun", "Human Beings"),
  Card(36, 36, "die Jacke", "Jacken", "jacket", "noun", "Human Beings"),
  Card(37, 37, "die Tasche", "Taschen", "bag", "noun", "Human Beings"),
  Card(38, 38, "die Brille", "Brillen", "glasses", "noun", "Human Beings"),
  Card(39, 39, "der Regenschirm", "Regenschirme", "umbrealla", "noun", "Human Beings"),
  Card(40, 40, "die Familie", "Familien", "family", "noun", "Social Relationships"),
  Card(41, 41, "die Eltern", "", "parents", "noun", "Social Relationships"),
  Card(42, 42, "die Mutter", "Mütter", "mother", "noun", "Social Relationships"),
  Card(43, 43, "der Vater", "Väter", "father", "noun", "Social Relationships"),
  Card(44, 44, "das Kind", "Kinder", "child, Pl. children", "noun", "Social Relationships"),
  Card(45, 46, "die Tochter", "Töchter", "daughter", "noun", "Social Relationships"),
  Card(46, 47, "der Sohn", "Söhne", "son", "noun", "Social Relationships"),
  Card(47, 48, "der Bruder", "Brüder", "brother", "noun", "Social Relationships"),
  Card(48, 49, "die Schwester", "Schwestern", "sister", "noun", "Social Relationships"),
  Card(49, 50, "der Mann, Ehemann", "Männer", "husband", "noun", "Social Relationships"),
  Card(50, 51, "die Frau, Ehefrau", "Frauen", "wife", "noun", "Social Relationships"),
  Card(51, 52, "die Oma", "Omas", "grandmother", "noun", "Social Relationships"),
  Card(52, 53, "der Opa", "Opas", "grandfather", "noun", "Social Relationships"),
  Card(53, 54, "das Enkelkind", "Enkelkinder", "grandchild", "noun", "Social Relationships"),
  Card(54, 55, "der Enkel", "Enkel", "grandson", "noun", "Social Relationships"),
  Card(55, 56, "die Enkelin", "Enkelinnen", "granddaughter", "noun", "Social Relationships"),
  Card(56, 57, "die Tante", "Tanten", "aunt", "noun", "Social Relationships"),
  Card(57, 58, "der Onkel", "Onkel", "uncle", "noun", "Social Relationships"),
  Card(58, 59, "der Freund", "Freunde", "friend, boyfriend", "noun", "Social Relationships"),
  Card(59, 60, "die Freundin", "Freundinnen", "firend, girlfriend", "noun", "Social Relationships"),
  Card(60, 61, "der Nachbar, die Nachbarin", "Nachbarn, Nachbarinnen", "neighbour", "noun", "Social Relationships"),
  Card(61, 62, "einladen", "", "to invite", "verb", "Social Relationships"),
  Card(62, 63, "kennen", "", "to know", "verb", "Social Relationships"),
  Card(63, 64, "wissen", "", "to know", "verb", "Social Relationships"),
  Card(64, 65, "die Menschen", "", "people", "noun", "Social Relationships"),
  Card(65, 66, "denken", "", "to think", "verb", "Thinking, Feeling"),
  Card(66, 67, "glauben", "", "to think, to believe", "verb", "Thinking, Feeling"),
  Card(67, 68, "sich fühlen", "", "to feel", "verb", "Thinking, Feeling"),
  Card(68, 69, "hören", "", "to hear", "verb", "Thinking, Feeling"),
  Card(69, 70, "sehen", "", "to see", "verb", "Thinking, Feeling"),
  Card(70, 71, "hoffen", "", "to hope", "verb", "Thinking, Feeling"),
  Card(71, 72, "sich erinnern", "", "to remember", "verb", "Thinking, Feeling"),
  Card(72, 73, "versprechen", "", "to promise", "verb", "Thinking, Feeling"),
  Card(73, 74, "vergessen", "", "to forget", "verb", "Thinking, Feeling")
];